/**
 * Turns an image into ASCII art and appends it to src/fs/ascii.ts.
 *
 * Generated and committed, like the logos, so nothing decodes images at runtime
 * and the result is reviewable as text in the repo.
 *
 * Usage:
 *   node scripts/generate-ascii.mjs <key> <image> [--cols 100] [--invert]
 *
 * --invert suits art on a light background: the subject is dark in the source
 * but needs to be the bright part on a dark terminal.
 */
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'

/** Sparse to dense. A space for the background keeps the silhouette clean. */
const RAMP = ' .:-=+*#%@'

/**
 * A monospace cell is far taller than it is wide, so rows must be squashed or
 * the picture comes out stretched. 0.602 is 9.03px / 15px, measured from the
 * rendered terminal at the line-height photos use.
 */
const CELL_ASPECT = 0.602

const [key, image, ...rest] = process.argv.slice(2)
if (!key || !image) {
  console.error('usage: node scripts/generate-ascii.mjs <key> <image> [--cols N] [--invert]')
  process.exit(1)
}

const cols = Number(rest[rest.indexOf('--cols') + 1]) || 100
const invert = rest.includes('--invert')

const size = execFileSync('magick', ['identify', '-format', '%w %h', image], { encoding: 'utf8' })
const [srcWidth, srcHeight] = size.trim().split(' ').map(Number)
const rows = Math.max(1, Math.round(srcHeight * (cols / srcWidth) * CELL_ASPECT))

// P2 is plain-text PGM: one grey value per pixel, trivial to parse without a
// decoding library.
const pgm = execFileSync(
  'magick',
  [image, '-resize', `${cols}x${rows}!`, '-colorspace', 'Gray', '-depth', '8', '-compress', 'none', 'pgm:-'],
  { encoding: 'latin1', maxBuffer: 64 * 1024 * 1024 },
)

const tokens = pgm
  .split('\n')
  .filter((line) => !line.startsWith('#'))
  .join(' ')
  .trim()
  .split(/\s+/)

if (tokens[0] !== 'P2') throw new Error(`expected a P2 pgm, got ${tokens[0]}`)
const width = Number(tokens[1])
const height = Number(tokens[2])
const max = Number(tokens[3])
const pixels = tokens.slice(4).map(Number)

const art = []
for (let y = 0; y < height; y++) {
  let line = ''
  for (let x = 0; x < width; x++) {
    const value = pixels[y * width + x] / max
    const level = invert ? 1 - value : value
    line += RAMP[Math.min(RAMP.length - 1, Math.round(level * (RAMP.length - 1)))]
  }
  // Trailing blanks are invisible and only pad the file.
  art.push(line.replace(/\s+$/, ''))
}

const file = 'src/fs/ascii.ts'
const header = `// GENERATED by scripts/generate-ascii.mjs. Do not edit by hand.
//
// Images rendered onto the character grid, so they take the terminal's colour
// and scale with its text instead of being pasted on as pictures.

export const ASCII: Record<string, string[]> = {
`

const existing = existsSync(file) ? readFileSync(file, 'utf8') : header + '}\n'
const entry = `  ${key}: [\n${art.map((line) => `    ${JSON.stringify(line)},`).join('\n')}\n  ],\n`

const withoutKey = existing.replace(new RegExp(`  ${key}: \\[[^\\]]*\\],\\n`), '')
writeFileSync(file, withoutKey.replace(/\}\n$/, entry + '}\n'))

console.log(`wrote ${key} to ${file}: ${width}x${height} characters`)
