/**
 * Writes src/fs/icons.ts from simple-icons.
 *
 * The paths are generated and committed so `simple-icons` stays a dev
 * dependency: the package carries 3400+ icons and none of it should end up in
 * the bundle just to draw eighteen logos.
 *
 * Run with: node scripts/generate-icons.mjs
 */
import { writeFileSync } from 'node:fs'
import * as simpleIcons from 'simple-icons'

/**
 * Display name -> simple-icons title.
 *
 * Java is deliberately mapped to OpenJDK: Java's own mark is excluded from
 * simple-icons over trademark, and OpenJDK is the reference implementation, so
 * its logo is the accepted stand-in.
 */
const WANTED = {
  python: 'Python',
  typescript: 'TypeScript',
  javascript: 'JavaScript',
  elixir: 'Elixir',
  java: 'OpenJDK',
  react: 'React',
  nextjs: 'Next.js',
  tailwind: 'Tailwind CSS',
  html: 'HTML5',
  css: 'CSS',
  node: 'Node.js',
  fastapi: 'FastAPI',
  graphql: 'GraphQL',
  postgresql: 'PostgreSQL',
  mysql: 'MySQL',
  databricks: 'Databricks',
  gcp: 'Google Cloud',
  docker: 'Docker',
  git: 'Git',
  posit: 'Posit',
}

const byTitle = new Map()
for (const icon of Object.values(simpleIcons)) {
  if (icon && typeof icon === 'object' && 'title' in icon && 'path' in icon) {
    byTitle.set(icon.title, icon)
  }
}

const entries = []
const missing = []
for (const [key, title] of Object.entries(WANTED)) {
  const icon = byTitle.get(title)
  if (!icon) {
    missing.push(`${key} (${title})`)
    continue
  }
  entries.push(`  ${key}: '${icon.path.replace(/'/g, "\\'")}',`)
}

if (missing.length) {
  console.error('No icon found for: ' + missing.join(', '))
  process.exit(1)
}

const banner = `// GENERATED by scripts/generate-icons.mjs. Do not edit by hand.
//
// Single-path monochrome logos from simple-icons, on a 24x24 viewBox. They are
// tinted by CSS (fill: currentColor), so they take the terminal's colour rather
// than each brand's.
//
// \`java\` is OpenJDK's mark: Java's own logo is excluded from simple-icons over
// trademark, and OpenJDK is the reference implementation.

export const ICONS: Record<string, string> = {
`

writeFileSync('src/fs/icons.ts', banner + entries.join('\n') + '\n}\n')
console.log(`wrote src/fs/icons.ts with ${entries.length} icons`)
